### ISSUE TITLE
Place focus on last added shopping cart item

### ISSUE THREAD

**Issue by ericlp** [Portals/iMat#23]
looks cooler

**Comment by ChalmersBock** [comment]
Now jumps to the bottom if the added item is new. Does nothing if just adding more to an already existing item

**Comment by ChalmersBock** [comment]
Now jumps correctly no matter if the item has already been added. The topmost item causes some problems, but the amount is still visible, so it's a minor problem. The code binds the vertical property of the scrollPane when adding a new item, and unbinds it when adding an old item.
